name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build docker image
      run: docker build . --tag bessarabov/save_advent_of_code_private_leaderboard_json:${{ github.ref_name }}

    - name: Push docker image
      run: docker push bessarabov/save_advent_of_code_private_leaderboard_json:${{ github.ref_name }}
